#!/bin/bash


# run_every [MILISECONDS] [COMMAND]
run_every() {
    command=${@:2}
    path=~/.BIN-DATA/pxh612-DAEMON-execute-"$command"

    milisecondsWait=$(($1))
    milisecondsNow=$(date +%s%3N)

    if [ -e "$path" ]
    then
        milisecondsDone=$(cat "$path")
    else
        echo $milisecondsNow > "$path"
    fi
    if [ $((milisecondsNow-milisecondsDone)) -gt $milisecondsWait ]
    then
        echo "$command executed"
        echo $milisecondsNow > "$path"
        $command 1>/dev/null 2>&1 &
    fi
}

# Unit = miliseconds
run_every 500 pxh612-info -s  
run_every 500 pxh612-INFO-memory-notifyLowMemory
run_every 500 pxh612-moveDownloads

SEC=1000
run_every 15*$SEC pxh612-INFO-internetSpeed-getSpeed

MIN=60*$SEC
run_every 5*$MIN pxh612-gitPush
