#!/bin/sh
path=$HOME/.BIN-DATA/pxh612-INFO-internetSpeed-getSpeed

speed=$(speedtest-cli --secure --simple --no-upload | grep -P -o '\bDownload:\s+\K\S+' )
speedMB=$(echo "scale = 2; $speed / 8" | bc )
	
echo $speed 
echo $speedMB
echo $speed  > $path-speed
echo $speedMB > $path-speedMB 

echo done.